### ISSUE TITLE
Template Elements

### ISSUE THREAD

**Issue by tpreusse** [orbiting/pdf#11]
Currently we have [3 main templates](https://styleguide.republik.ch/templates/front):
- `article`
- `newsletter`
- `front`

The article is template is configurable and has 3 sub templates: `discussion`, `format` and `dossier`. Those sub templates only modify the title block: `dossier` prepending a label and `format` replacing the title block with a custom implementation without credit line.

**The primary goal is to support the main `article` template for pdf rendering.**

All templates by priority
1. `article`
2. `newsletter`
3. `dossier`
4. `discussion`
5. `format`

Currently there is no need to support `front`. It would need a pdf usage concept first.

## Elements in `article` template

- [Documentation](https://styleguide.republik.ch/templates/article)
- [Schema Code](https://github.com/orbiting/styleguide/blob/master/src/templates/Article/index.js)

### ToDo

- [x] title block
  - [x] center
- [x] center
- [x] paragraph
- [x] global inline elements
  - [x] bold
  - [x] link
  - [x] break (new line)
  - [x] italic
  - [sub and super script](https://styleguide.republik.ch/typography#sub-and-super-script)
    - [x] sub
    - [x] sup
- [x] figure
  - [x] caption
  - [x] caption credit
  - [x] sizes: normal (text column width), full width but not borderless (edge-to-edge and breakout)
  - [x] as a cover
- [x] figure group
- [x] block quote
- [x] pull quote
  - [x] figure
  - [x] figure caption
  - [x] sizes: always `narrow`—centered text unless with figure
- [x] infobox
  - [x] figure
  - [x] figure caption
  - [x] sizes: always `regular`, figureSize always M-ish
- [x] thematic break (aka hr)
- [x] note zone (small sans-serif text)

**Note regarding sizes**: on the web we support many sizes. For an initial pdf renderer we want to boil it down: two sizes for figure, one sizes for pull quote and info box.

### Render as Image

- [x] charts
- [x] article collection
- [x] video
- [x] audio
- [x] tweet

**Comment by tpreusse** [comment]
Target Layout
[O011_Web2PDF.pdf](https://github.com/orbiting/poc-pdf/files/1918480/O011_Web2PDF.pdf)
Ignore: printed links. We won't print the url as in the design, it will distract too much. Just regular links that are clickable when read digitally.

Font Sizes

| area        | type          | points | example text                     |
|-------------|---------------|--------|----------------------------------|
| title block | format        | 10     | Debatte                          |
| title block | title         | 30     | Freuen Sie sich auf Olympia?     |
| title block | lead          | 12     | Dass heute alle Welt...          |
| title block | credit        | 7      | Von Sylke Gruhnwald...           |
| center      | paragraph     | 10     | Es beginnt damit, dass...        |
| center      | pull quote    | 13     | Dass heute alle Welt Bescheid... |
| center      | h2            | 13     | 1. Versuch: Flasche              |
| figure      | legend        | 7      | In präparierten Blutbeuteln      |
| figure      | credit        | 6      | Maurizio di Iorio                |
| infobox     | title         | 10     | Die Kooperation                  |
| infobox     | paragraph     | 9      | Zur «Geheimsache Doping»...      |
| infobox     | figure legend | 7      | Matthias Kamber...               |
| infobox     | figure credit | 6      | zvg                              |

**Comment by tpreusse** [comment]
# Key Screens of PDF-Elements from the Design Team

## Title Block

### Regular
<img width="611" alt="screen shot 2018-04-17 at 09 30 09" src="https://user-images.githubusercontent.com/410211/38854835-088c7a98-4222-11e8-8819-0be2884b6b74.png">

### Center
<img width="563" alt="screen shot 2018-04-17 at 09 37 23" src="https://user-images.githubusercontent.com/410211/38855160-03e36910-4223-11e8-965a-e6af57df708f.png">


## Figure

### Full-Width
<img width="610" alt="screen shot 2018-04-17 at 09 29 40" src="https://user-images.githubusercontent.com/410211/38854861-20ff4b82-4222-11e8-8fae-07bd2c57f030.png">

### Column-Width
<img width="582" alt="screen shot 2018-04-17 at 09 32 18" src="https://user-images.githubusercontent.com/410211/38854898-44631f5e-4222-11e8-838e-99d9f8f351fe.png">

## Figure Group
<img width="518" alt="screen shot 2018-04-17 at 09 32 59" src="https://user-images.githubusercontent.com/410211/38854938-5e81167a-4222-11e8-89c1-994a0c1523d6.png">

_Always full-width, this is a global caption (see fixture)_

## Infobox

### Without an Image
<img width="446" alt="screen shot 2018-04-17 at 09 34 41" src="https://user-images.githubusercontent.com/410211/38855038-a593c792-4222-11e8-8a5f-60d910fb4878.png">

### With an Image
<img width="456" alt="screen shot 2018-04-17 at 09 35 37" src="https://user-images.githubusercontent.com/410211/38855065-ba24d2dc-4222-11e8-929a-1d60d179964c.png">



## Pull Quote

<img width="395" alt="screen shot 2018-04-17 at 09 38 28" src="https://user-images.githubusercontent.com/410211/38855199-26f25d58-4223-11e8-869d-be60f6bd9372.png">

_with an image is missing, implement layout with image [according to styleguide](https://styleguide.republik.ch/pullquote)_

## Note
<img width="455" alt="screen shot 2018-04-17 at 09 36 31" src="https://user-images.githubusercontent.com/410211/38855101-d831f7e6-4222-11e8-950c-a1a10197d0da.png">

**Comment by diegomura** [comment]
## Progress:
Here I'll upload element samples to see how they currently look

**Infobox:**
[infoboxes.pdf](https://github.com/orbiting/pdf/files/1924935/infoboxes.pdf)

**Comment by diegomura** [comment]
@tpreusse question:
- `italic` (or `emphasis` ) will need a new font types right?
- I couldn't find examples of these cases:
  - figure with caption credit
  - figure as a cover
  - block quote
  - pull quote with image
  - note zone
